### ISSUE TITLE
Can't find tinyxml2.a on Linux x64

### ISSUE THREAD

**Issue by mertcanekiz** [Twinklebear/asteroids#1]
I am trying to build this on Arch Linux x64 but I am having some issues. I make 'build' directory and cd into it, then I do 'cmake ..' and it finishes without any errors. When I try to run make, I get this error:

``` make
[ 58%] Completed 'tinyxml2'
[ 66%] Built target tinyxml2
make[2]: *** No rule to make target '../external/tinyxml2/lib/libtinyxml2.a', needed by 'src/Asteroids'.  Stop.
CMakeFiles/Makefile2:196: recipe for target 'src/CMakeFiles/Asteroids.dir/all' failed
make[1]: *** [src/CMakeFiles/Asteroids.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

There is no lib directory in ../external/tinyxml2 but there is a lib64 directory. So I tried renaming it to lib but it still doesn't work.

**Comment by Twinklebear** [comment]
Maybe try changing [this line](https://github.com/Twinklebear/asteroids/blob/master/CMakeLists.txt#L23) to:

``` cmake
set(tinyxml2_LIBRARY "${tinyxml2_DIR}/lib64/libtinyxml2.a")
```

The way the downloading and building of the libraries is set up is not that portable. The only machines I tested it on are my laptop and desktop with Windows and MinGW, since this is really just a personal project.

Let me know if that works though!

**Comment by mertcanekiz** [comment]
Okay, changing tinyxml2_LIBRARY to "${tinyxml2_DIR}/lib64/libtinyxml2.so" solved the problem.. But now when I run I just see some tiles on the screen.. Is that what I'm supposed to be seeing?

**Comment by Twinklebear** [comment]
Yep, so as I mentioned this project is really not a finished game or anything. The tiles are testing the render batch and texture atlas array stuff. Initially I was planning on making a modern OpenGL asteroids but it kind of devolved into template/OpenGL experiments.

**Comment by Twinklebear** [comment]
If you change the call to `tile_demo` [here](https://github.com/Twinklebear/asteroids/blob/master/src/main.cpp#L69) to call `run` instead it'll show some 'asteroids' moving around where you can control one of them with the keyboard if I recall correctly.

**Comment by mertcanekiz** [comment]
Oh I see.. I should have read the README a little bit more carefully :) Thanks for your help
