### ISSUE TITLE
libxml2.a missing

### ISSUE THREAD

**Issue by heeen** [Twinklebear/asteroids#2]
libxml2.a is not part of the external project. suggesting to use pkgconf to find system libxml2

**Comment by Twinklebear** [comment]
I'm not sure if I'll get back to this project but a good fix here would be to try FindPackage to find it on yhr system and if it's not found build the external project. I'll keep this issue open to remember.

Thanks for the bug report!

**Comment by MelomanCool** [comment]
Turns out, when building on a linux system, that library simply have other extension. Changing .a to .so fixed the problem for me.

**Comment by Twinklebear** [comment]
Interesting, it must default to building a shared lib then. I can update the library search. Thanks @MelomanCool

**Comment by Twinklebear** [comment]
fb8a368860daa1f35782a081179e048342edd3a5 should fix this, let me know if you run into issues. I haven't worked on this project much so just did the change in online and haven't tested building it

**Comment by MelomanCool** [comment]
Yes, works just fine.
